language: go

install:
  - grep 'import' -rl ./| grep ".go"| xargs sed -i 's#"dad-go/#"github.com/DAD-Chain/dad-go/#g'
  - go get github.com/Masterminds/glide
  - glide install

go:
  - 1.7.x
  - master
