language: go

go_import_path: github.com/ontio/dad-go

install:
  - go get github.com/Masterminds/glide
  - glide install

go:
  - 1.12.x

script:
  - bash ./.travis.check-license.sh
  - bash ./.travis.gofmt.sh
  - make all-cross
  - bash ./.travis.gotest.sh
